### ISSUE TITLE
Login form POSTs instead of preventing default

### ISSUE THREAD

**Issue by Fermain** [JoranEngelund/Social-Media-Application#24]
When running this application on localhost with the command `npm run watch`, the login form fails.

This is because I am viewing: `http://127.0.0.1:8080/`

And the router is set to listen for `/index.html`:

```js
if (path === "/index.html")
```

Changing this to `http://127.0.0.1:8080/index.html` resolves this issue but this is not best practice. Suggest updating the router code to accept either scenario.

**Comment by JoranEngelund** [comment]
Will do. But wont the port change for every user? `http://127.0.0.1:8080/` you get `:8080` while on my end I have `http://127.0.0.1:5500/`

Nvm - I managed to find the hostname and port the url is using with `window.location.port` and `window.location.hostname`
